--- 
build_requires: 
  IPC::Run3: 0
  RunApp: 0.13
  Test::Output: 0
distribution_type: module
generated_by: Module::Install version 0.650
license: unknown
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Pushmi
no_index: 
  directory: 
    - inc
    - t
requires: 
  App::CLI: 0.06
  Cache::Memcached: 0
  Log::Log4perl: 0
  SVK: 2.0.0
  SVN::Core: 1.004003
  YAML::Syck: 0
  version: 0
version: !!perl/hash:version 
  qv: 1
  version: 
    - 0
    - 992
    - 0
